import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const helvetica = localFont({
  src: "./Helvetica.ttf",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${helvetica.className} antialiased`}>{children}</body>
    </html>
  )
}
